### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#11]
Types are always capitalized in Java (that is, classes, interfaces, enums, etc...)

https://github.com/adiwir/TDA553-lab2/blob/7f26da90d6cb1168d4196ff6f273ef66f8bf6abc/src/labb/Car.java#L15

**Comment by JacobAndersso** [comment]
Has been fixed https://github.com/adiwir/TDA553-lab2/blob/3d668a68371aca589f77f4f37e441028cabd0e11/src/labb/Car.java#L16

**Comment by martinjonsson01** [comment]
Ah, it wasn't present in the version you put the "Lab2" tag on. Be sure to update the tags whenever you make changes you want me to see!
