### ISSUE TITLE
CRITICAL: Scania can move while platform is raised

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#23]
I can call `startEngine()` on Scania while its platform is raised, making it accelerate a tiny bit. Then when I call `move()` it will move, even though the platform is raised.
https://github.com/adiwir/TDA553-lab2/blob/7f26da90d6cb1168d4196ff6f273ef66f8bf6abc/src/labb/Car.java#L73-L75

You're only checking the angle when `gas` is called, never when `startEngine` is called.
https://github.com/adiwir/TDA553-lab2/blob/7f26da90d6cb1168d4196ff6f273ef66f8bf6abc/src/labb/Scania.java#L18-L23

**Comment by JacobAndersso** [comment]
Overrides startEngine to prevent Scania and CarTransporter from moving when platform is angled. 5faef44

**Comment by martinjonsson01** [comment]
A tip: include a reference to the issue number by writing "#23" in your commit message somewhere, that way it'll get linked to the issue automatically! :)
