### ISSUE TITLE
CRITICAL: MVC: This code should be in one or more of the Controllers, because it is about taking input from the user, not telling the user the state of the model. 

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#28]
(Hint; It will be easiest if you make all the code relating to the buttons and spinner into Controllers.)

https://github.com/adiwir/TDA553-lab2/blob/114f866b2ed61ea83c9aad137ea967b477833086/src/mvc/CarView.java#L101-L106
https://github.com/adiwir/TDA553-lab2/blob/114f866b2ed61ea83c9aad137ea967b477833086/src/mvc/CarView.java#L62-L67

**Comment by martinjonsson01** [comment]
That works 👍 

Please create a new tag for this fix, then I'll be able to mark it as resolved and pass you in Canvas!

**Comment by JacobAndersso** [comment]
Done!
