### ISSUE TITLE
Bad practice: Using an integer to represent known constants

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#8]
Here you're using an integer to represent direction, with different values representing specific directions. It's very difficult to know which number corresponds to which direction without reading the rest of your code. It's also very easy to accidentally input an invalid number, like a negative number or a number that is way too big. 

Instead, you should use [enums ](https://www.w3schools.com/java/java_enums.asp) - this is what they're made for! 

https://github.com/adiwir/TDA553-lab1/blob/2c98dd2231e2bb8ac52cc6d83b46fc251e242f7e/src/labb/Car.java#L13

**Comment by JacobAndersso** [comment]
Implemented enums instead.
