### ISSUE TITLE
Unnecessary clamping

### ISSUE THREAD

**Issue by martinjonsson01** [adiwir/TDA553-lab1#9]
If currentSpeed is less than `0`, then `Math.max(currentSpeed, 0)` will always evaluate to `0`. You might as well just replace it with `this.currentSpeed = 0;`, since that is much clearer. 

https://github.com/adiwir/TDA553-lab1/blob/2c98dd2231e2bb8ac52cc6d83b46fc251e242f7e/src/labb/Car.java#L46-L48

**Comment by JacobAndersso** [comment]
Implemented the suggested change.
